#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <proto_filename>"
    exit 1
fi

PROTO_FILE="$1"

if [ ! -f "$PROTO_FILE" ]; then
    echo "File not found: $PROTO_FILE"
    exit 1
fi

PROTO_BASENAME_NO_EXT=$(basename "$PROTO_FILE" .proto)
PROTO_DIR="./src/models/proto_models/$PROTO_BASENAME_NO_EXT"
mkdir -p "$PROTO_DIR"

PROTO_BASENAME=$(basename "$PROTO_FILE")

PROTO_FILE_DIR=$(dirname "$PROTO_FILE")

protoc --proto_path="$PROTO_FILE_DIR" \
    --grpc_out="$PROTO_DIR" \
    --plugin=protoc-gen-grpc="$(which grpc_cpp_plugin)" \
    "$PROTO_FILE"

protoc --proto_path="$PROTO_FILE_DIR" \
    --cpp_out="$PROTO_DIR" \
    "$PROTO_FILE"